version: '3.8'

networks:
  localstack-network:

services:
  # https://hub.docker.com/r/localstack/localstack
  localstack:
    container_name: localstack-dev
    profiles:
      - dev
    image: localstack/localstack:1.4
    ports:
      - "4566:4566"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_REGION=eu-central-1
      - EDGE_PORT=4566
      - SERVICES=s3,kms,lambda,sqs,secretmanager,iam
      - AWS_ENVIRONMENT=local
      - AWS_ACCESS_KEY_ID=testkey
      - AWS_SECRET_ACCESS_KEY=test
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - localstack-network
  
  terraform-cli:
    container_name: terraform-cli
    build:
      context: .
      dockerfile: terraform.Dockerfile
    depends_on:
      - localstack
    environment:
      - ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=testkey
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_DEFAULT_REGION=eu-central-1
    networks:
      - localstack-network
    

